package quanlykhachsan;
// Generated May 30, 2019 12:16:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chitiethoadon generated by hbm2java
 */
public class Chitiethoadon  implements java.io.Serializable {


     private int maCthd;
     private String maHd;
     private String maPhong;
     private Integer soNgayThue;
     private Float donGia;
     private Date ngayTao;

    public Chitiethoadon() {
    }

	
    public Chitiethoadon(int maCthd, String maHd, String maPhong) {
        this.maCthd = maCthd;
        this.maHd = maHd;
        this.maPhong = maPhong;
    }
    public Chitiethoadon(int maCthd, String maHd, String maPhong, Integer soNgayThue, Float donGia, Date ngayTao) {
       this.maCthd = maCthd;
       this.maHd = maHd;
       this.maPhong = maPhong;
       this.soNgayThue = soNgayThue;
       this.donGia = donGia;
       this.ngayTao = ngayTao;
    }
   
    public int getMaCthd() {
        return this.maCthd;
    }
    
    public void setMaCthd(int maCthd) {
        this.maCthd = maCthd;
    }
    public String getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(String maHd) {
        this.maHd = maHd;
    }
    public String getMaPhong() {
        return this.maPhong;
    }
    
    public void setMaPhong(String maPhong) {
        this.maPhong = maPhong;
    }
    public Integer getSoNgayThue() {
        return this.soNgayThue;
    }
    
    public void setSoNgayThue(Integer soNgayThue) {
        this.soNgayThue = soNgayThue;
    }
    public Float getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(Float donGia) {
        this.donGia = donGia;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }




}


