package quanlykhachsan;
// Generated May 30, 2019 11:49:09 AM by Hibernate Tools 4.3.1



/**
 * Loaiphong generated by hbm2java
 */
public class Loaiphong  implements java.io.Serializable {


     private int maLoai;
     private String tenLoai;
     private Float donGia;

    public Loaiphong() {
    }

	
    public Loaiphong(int maLoai) {
        this.maLoai = maLoai;
    }
    public Loaiphong(int maLoai, String tenLoai, Float donGia) {
       this.maLoai = maLoai;
       this.tenLoai = tenLoai;
       this.donGia = donGia;
    }
   
    public int getMaLoai() {
        return this.maLoai;
    }
    
    public void setMaLoai(int maLoai) {
        this.maLoai = maLoai;
    }
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }
    public Float getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(Float donGia) {
        this.donGia = donGia;
    }




}


