/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykhachsan;

import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javafx.scene.paint.Color;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Phung
 */
public class MainMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuFrame
     */
    //JButton jbut = new JButton("jButton1");
    public MainMenuFrame() {
        initComponents();
        JMenuBar menubar = new JMenuBar();
        ImageIcon icon = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/new.png").getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT));
        JMenu file = new JMenu("File");
        file.setMnemonic(KeyEvent.VK_F);
  
        JMenuItem eMenuItem = new JMenuItem("Exit", icon);
        eMenuItem.setMnemonic(KeyEvent.VK_E);
        eMenuItem.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                System.exit(0); 
            }
        });
        file.add(eMenuItem);
        menubar.add(file);
  
        setJMenuBar(menubar);
        setTitle("LegendSoft - 1.0");
        
        // button mượn phòng room
        ImageIcon iconKey = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/key2.png").getImage().getScaledInstance(60,60, Image.SCALE_DEFAULT));
        this.btnKey.setIcon(iconKey);
        
       // button danh sách phòng
       ImageIcon iconRoom = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/hotel.png").getImage().getScaledInstance(60,60, Image.SCALE_DEFAULT));
       this.btnRoom.setIcon(iconRoom);
       
       // button doanh thu
        ImageIcon iconDiagram = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/diagram.png").getImage().getScaledInstance(60,60, Image.SCALE_DEFAULT));
        this.btnDoanhThu.setIcon(iconDiagram);
        
        //button Setting
        ImageIcon iconSetting = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/setting.png").getImage().getScaledInstance(60,60, Image.SCALE_DEFAULT));
        this.btnSetting.setIcon(iconSetting);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRoom = new javax.swing.JButton();
        btnKey = new javax.swing.JButton();
        btnDoanhThu = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        btnRoom.setText("jH");
        btnRoom.setActionCommand("jHotel");
        btnRoom.setAlignmentY(0.0F);
        btnRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRoomMouseClicked(evt);
            }
        });

        btnKey.setAlignmentY(0.0F);
        btnKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeyMouseClicked(evt);
            }
        });
        btnKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeyActionPerformed(evt);
            }
        });

        btnDoanhThu.setText("jButton1");
        btnDoanhThu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnSetting.setText("jButton1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKey, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnKey, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeyActionPerformed

    private void btnKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeyMouseClicked
        // TODO add your handling code here:
        ImagePanel panel = new ImagePanel(new ImageIcon("D:/LegendSoft/Images/bg12.jpg").getImage());
        DSPhongTrongFrame room = new DSPhongTrongFrame();
        room.getContentPane().add(panel);
        room.setVisible(true);
        room.setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE);
        /* JOptionPane.showConfirmDialog((Component) null, "User không được cho phép vào phòng chat", "Thông báo",  JOptionPane.OK_OPTION);
         testin test = new testin();
         test.setVisible(true);
        test.setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE);*/
        
    }//GEN-LAST:event_btnKeyMouseClicked

    private void btnRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoomMouseClicked
        // TODO add your handling code here:
        
        ImagePanel panel = new ImagePanel(new ImageIcon("D:/LegendSoft/Images/bg7.jpg").getImage());
        DSPhongFrame room = new DSPhongFrame();
        room.getContentPane().add(panel);
        room.setVisible(true);
        room.setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
     
    }//GEN-LAST:event_btnRoomMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
    }

    void setIconImage(String backgroundjpg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoanhThu;
    private javax.swing.JButton btnKey;
    private javax.swing.JButton btnRoom;
    private javax.swing.JButton btnSetting;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
