/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykhachsan.view;

import java.awt.Component;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlykhachsan.*;
import quanlykhachsan.view.*;
import quanlykhachsan.dao.*;
import quanlykhachsan.entity.*;
/**
 *
 * @author Phung
 */
public class ThueFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThueFrame
     */
     DefaultComboBoxModel modelCombox;
     DefaultTableModel modeltable;
     
    int SLKH = 0;
    float TongTien = 0;
    float donGia = 0;
    CaiDatDao cdDao = new CaiDatDao();
    Caidat cd = cdDao.getCaiDat();  
    LoaiKhachDao lkhachDao = new LoaiKhachDao();
    PhongDao pDao = new PhongDao();
    PhieuThuePhongDao thuepDao = new PhieuThuePhongDao();
    int maphong = 0;
    
    int maphieuthuephong = 0;
    List<Phieuthuekhachhang> khList = new ArrayList <Phieuthuekhachhang>();
    
    float heSoKhach = 1;
    public ThueFrame() {
        initComponents();
        ImagePanel panel = new ImagePanel(new ImageIcon("D:/LegendSoft/Images/bg12.jpg").getImage());
        getContentPane().add(panel);
        
        ImageIcon iconExit = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/exit2.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnThue.setIcon(iconExit);
        
        ImageIcon iconAdd = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/add3.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnThem.setIcon(iconAdd);
        
        ImageIcon iconEdit = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/edit3.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnSua.setIcon(iconEdit);
        
        ImageIcon iconXoa = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/delete2.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnXoa.setIcon(iconXoa);
        
        ImageIcon iconRefresh = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/refresh.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnRefresh.setIcon(iconRefresh);
    }
    
    public ThueFrame(String tenPhong, float DonGia) {
        initComponents();
        ImagePanel panel = new ImagePanel(new ImageIcon("D:/LegendSoft/Images/bg12.jpg").getImage());
        getContentPane().add(panel);
        
        ImageIcon iconExit = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/exit2.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnThue.setIcon(iconExit);
         ImageIcon iconAdd = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/add3.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnThem.setIcon(iconAdd);
        
        ImageIcon iconEdit = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/edit3.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnSua.setIcon(iconEdit);
        
        ImageIcon iconXoa = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/delete2.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnXoa.setIcon(iconXoa);
        
        ImageIcon iconRefresh = new ImageIcon(new ImageIcon("D:/LegendSoft/Images/refresh.png").getImage().getScaledInstance(40,40, Image.SCALE_DEFAULT));
        this.btnRefresh.setIcon(iconRefresh);
        
        this.txtTenPhong.setText(tenPhong);
        this.txtTenPhong.setEditable(false);
        this.txtTongTien.setEditable(false);
        this.jDateChooser1.setEnabled(false);
        donGia = DonGia;
        
        String [] ColumNames={"Tên khách","Loại khách", "CMND", "Địa chỉ"}; 
        modeltable = new DefaultTableModel(null , ColumNames);
        loadTable();
        
       modelCombox = (DefaultComboBoxModel) cmbLoaiKhach.getModel();
       List<Loaikhach> lkList = lkhachDao.getlKhachList();
       hienthidsloaip(lkList); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbLoaiKhach = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThue = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Đăng ký thuê phòng");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên khách");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ngày thuê");

        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jDateChooser1.setEnabled(false);
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tên phòng");

        txtTenPhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Loại khách");

        cmbLoaiKhach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CMND");

        txtCMND.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Số điện thoại");

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Địa chỉ");

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnThue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThue.setText("Thuê");
        btnThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThueMouseClicked(evt);
            }
        });
        btnThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThueActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRefresh.setText("Refesh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tổng tiền");

        txtTongTien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTongTien.setText("0");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("VND");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(136, 136, 136)
                                .addComponent(cmbLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(267, 267, 267)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel10)))
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(63, 63, 63)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSDT)
                                .addComponent(txtCMND, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThue, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(315, 315, 315))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cmbLoaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(238, 238, 238))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThueMouseClicked
        // TODO add your handling code here:
        if(khList.isEmpty() || khList == null)
        {
            JOptionPane.showConfirmDialog((Component) null, "Vui lòng thêm thông tin khách hàng thuê", "Yêu cầu", JOptionPane.CLOSED_OPTION);
        }
        else
        {
            float hs = 1;
            boolean kq = false;
            PhieuThueKhachHangDao pthuekhDao = new PhieuThueKhachHangDao();
            for(int i = 0; i < khList.size(); i++)
            {
                Phieuthuekhachhang kh = khList.get(i);
                Loaikhach lk = lkhachDao.getLoaiByID(kh.getLoaiKhach());
                if(hs < lk.getHeSo())
                {
                    hs = lk.getHeSo();
                }
               kq = pthuekhDao.themKH(kh);
            }
            float tt = hs * TongTien;
            thuepDao.tinhTien(tt, maphieuthuephong);
            if(kq == true)
            {
                 JOptionPane.showConfirmDialog((Component) null, "Đã thuê phòng " + this.txtTenPhong.getText() + " với giá " +tt+ " một ngày", "Thông báo", JOptionPane.CLOSED_OPTION);
                 this.setVisible(false);
                 DSPhongTrongFrame room = new DSPhongTrongFrame();
                room.setVisible(true);
                room.setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE);
            }
            
        }
    }//GEN-LAST:event_btnThueMouseClicked

    private void btnThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThueActionPerformed

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        SLKH = SLKH + 1;
        if(SLKH > cd.getSoKhachToiDa())
        {
            JOptionPane.showConfirmDialog((Component) null, "Đã quá số lượng khách cho phép", "Yêu cầu", JOptionPane.CLOSED_OPTION);
            SLKH = SLKH - 1;
        }
        else
        {
            Loaikhach lk = (Loaikhach) this.cmbLoaiKhach.getSelectedItem();
            if(SLKH  == 1)
            {
                TongTien = (float) donGia;
                if(this.maphieuthuephong == 0)
                {
                    List<Phong> p = pDao.timPhongByTen(this.txtTenPhong.getText());
                    Date daynow = new Date();
                    Phieuthuephong thuep = new Phieuthuephong (p.get(0).getMaPhong(), daynow, Float.valueOf(0), false); 
                    maphieuthuephong = thuepDao.themPhong(thuep);
                    pDao.thuePhong(p.get(0).getMaPhong());
                }
            }
            if (SLKH > 2)
            {
                TongTien = TongTien + (donGia * cd.getTyLePhuThu());
            }
            if(heSoKhach < lk.getHeSo())
            {
                heSoKhach = lk.getHeSo();
            }
            Phieuthuekhachhang kh = new Phieuthuekhachhang(maphieuthuephong,this.txtTenKH.getText(),lk.getMaLoai(), this.txtCMND.getText(), this.txtDiaChi.getText(), false);
            khList.add(kh);
            this.themKH(kh, lk);
        }
        this.txtTongTien.setText(String.valueOf(TongTien));
       
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
        this.txtTenKH.setText("");
        this.txtSDT.setText("");
        this.txtCMND.setText("");
        this.txtDiaChi.setText("");
        this.txtTongTien.setText("0");
        loadTable();
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() != -1)
        {
           int index = jTable1.getSelectedRow();
           SLKH = SLKH -1;
            if(SLKH < 0)
            {
                JOptionPane.showConfirmDialog((Component) null, "Không có khách nào để xóa", "Thông báo", JOptionPane.CLOSED_OPTION);
                SLKH = SLKH + 1;
            }
            else
            {
                String tenlKh = (String)(modeltable.getValueAt(index,1));
                Loaikhach lk = lkhachDao.TonTai(tenlKh);
                if(SLKH  == 0)
                {

                     TongTien = TongTien - (float) donGia;
                }
                if (SLKH == 2)
                {
                    TongTien = TongTien - (donGia * cd.getTyLePhuThu());
                }
                if(heSoKhach < lk.getHeSo())
                {
                    heSoKhach = lk.getHeSo();
                }
                Phieuthuekhachhang kh = new Phieuthuekhachhang(maphieuthuephong,this.txtTenKH.getText(),lk.getMaLoai(), this.txtCMND.getText(), this.txtDiaChi.getText(), false);
                khList.remove(kh);
                modeltable.removeRow(index);
            }
            this.txtTongTien.setText(String.valueOf(TongTien));
        }
         else
        {
             JOptionPane.showConfirmDialog((Component) null, "Vui lòng chọn khách hàng cần xóa", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() != -1)
        {
           int index = jTable1.getSelectedRow();
          // SLKH = SLKH -1;
            if(SLKH < 0)
            {
                JOptionPane.showConfirmDialog((Component) null, "Không có khách nào để sửa", "Thông báo", JOptionPane.CLOSED_OPTION);
              //  SLKH = SLKH + 1;
            }
            else
            {
                String tenlKh = (String)(modeltable.getValueAt(index,1));
                Loaikhach lk = lkhachDao.TonTai(tenlKh);
               /* if(SLKH  == 0)
                {

                     TongTien = TongTien - (float) donGia;
                }
                if (SLKH == 2)
                {
                    TongTien = TongTien - (donGia * cd.getTyLePhuThu());
                }*/
                if(heSoKhach < lk.getHeSo())
                {
                    heSoKhach = lk.getHeSo();
                }
                Phieuthuekhachhang kh = new Phieuthuekhachhang(maphieuthuephong,this.txtTenKH.getText(),lk.getMaLoai(), this.txtCMND.getText(), this.txtDiaChi.getText(), false);
                khList.set(index, kh);
                modeltable.removeRow(index);
                this.themKH(kh, lk);
            }
            this.txtTongTien.setText(String.valueOf(TongTien));
        }
         else
        {
             JOptionPane.showConfirmDialog((Component) null, "Vui lòng chọn khách hàng cần xóa", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    void loadTable()
    {
       modeltable.getDataVector().removeAllElements();
        jTable1.setModel(modeltable);
        jTable1.setRowHeight(30);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
        //jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
    }
    void themKH(Phieuthuekhachhang kh, Loaikhach lk)
    {  
        Object[] items = new Object[]{kh.getTenKhachHang(), lk.getTenLoai(), kh.getCmnd(), kh.getDiaChi()};
        modeltable.addRow(items);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThueFrame().setVisible(true);
            }
        });
    }
    void hienthidsloaip(List <Loaikhach> dslkhach) {

        modelCombox.removeAllElements();
        for (int i = 0; i < dslkhach.size(); i++) {
            Loaikhach a = (Loaikhach) dslkhach.get(i);
            modelCombox.addElement(a);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThue;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmbLoaiKhach;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
