package quanlykhachsan.entity;
// Generated Jun 13, 2019 4:36:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Caidat generated by hbm2java
 */
public class Caidat  implements java.io.Serializable {


     private Integer id;
     private Float tyLePhuThu;
     private Integer soKhachToiDa;
     private Date ngayBatDau;
     private Boolean xoa;

    public Caidat() {
    }

    public Caidat(Float tyLePhuThu, Integer soKhachToiDa, Date ngayBatDau, Boolean xoa) {
       this.tyLePhuThu = tyLePhuThu;
       this.soKhachToiDa = soKhachToiDa;
       this.ngayBatDau = ngayBatDau;
       this.xoa = xoa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Float getTyLePhuThu() {
        return this.tyLePhuThu;
    }
    
    public void setTyLePhuThu(Float tyLePhuThu) {
        this.tyLePhuThu = tyLePhuThu;
    }
    public Integer getSoKhachToiDa() {
        return this.soKhachToiDa;
    }
    
    public void setSoKhachToiDa(Integer soKhachToiDa) {
        this.soKhachToiDa = soKhachToiDa;
    }
    public Date getNgayBatDau() {
        return this.ngayBatDau;
    }
    
    public void setNgayBatDau(Date ngayBatDau) {
        this.ngayBatDau = ngayBatDau;
    }
    public Boolean getXoa() {
        return this.xoa;
    }
    
    public void setXoa(Boolean xoa) {
        this.xoa = xoa;
    }




}


