package quanlykhachsan.entity;
// Generated Jun 13, 2019 4:36:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hoadon generated by hbm2java
 */
public class Hoadon  implements java.io.Serializable {


     private Integer maHd;
     private Integer maPhong;
     private Integer maPhieuThue;
     private String tenKhachHang;
     private String diaChi;
     private Float donGia;
     private Integer soNgayThue;
     private Float triGia;
     private Date ngayTao;
     private Boolean xoa;

    public Hoadon() {
    }

    public Hoadon(Integer maPhong, Integer maPhieuThue, String tenKhachHang, String diaChi, Float donGia, Integer soNgayThue, Float triGia, Date ngayTao, Boolean xoa) {
       this.maPhong = maPhong;
       this.maPhieuThue = maPhieuThue;
       this.tenKhachHang = tenKhachHang;
       this.diaChi = diaChi;
       this.donGia = donGia;
       this.soNgayThue = soNgayThue;
       this.triGia = triGia;
       this.ngayTao = ngayTao;
       this.xoa = xoa;
    }
   
    public Integer getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(Integer maHd) {
        this.maHd = maHd;
    }
    public Integer getMaPhong() {
        return this.maPhong;
    }
    
    public void setMaPhong(Integer maPhong) {
        this.maPhong = maPhong;
    }
    public Integer getMaPhieuThue() {
        return this.maPhieuThue;
    }
    
    public void setMaPhieuThue(Integer maPhieuThue) {
        this.maPhieuThue = maPhieuThue;
    }
    public String getTenKhachHang() {
        return this.tenKhachHang;
    }
    
    public void setTenKhachHang(String tenKhachHang) {
        this.tenKhachHang = tenKhachHang;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Float getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(Float donGia) {
        this.donGia = donGia;
    }
    public Integer getSoNgayThue() {
        return this.soNgayThue;
    }
    
    public void setSoNgayThue(Integer soNgayThue) {
        this.soNgayThue = soNgayThue;
    }
    public Float getTriGia() {
        return this.triGia;
    }
    
    public void setTriGia(Float triGia) {
        this.triGia = triGia;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public Boolean getXoa() {
        return this.xoa;
    }
    
    public void setXoa(Boolean xoa) {
        this.xoa = xoa;
    }




}


