package quanlykhachsan.entity;
// Generated Jun 13, 2019 4:36:06 PM by Hibernate Tools 4.3.1



/**
 * Loaikhach generated by hbm2java
 */
public class Loaikhach  implements java.io.Serializable {


     private Integer maLoai;
     private String tenLoai;
     private Float heSo;
     private Boolean xoa;

    public Loaikhach() {
    }

    public Loaikhach(String tenLoai, Float heSo, Boolean xoa) {
       this.tenLoai = tenLoai;
       this.heSo = heSo;
       this.xoa = xoa;
    }
   
    public Integer getMaLoai() {
        return this.maLoai;
    }
    
    public void setMaLoai(Integer maLoai) {
        this.maLoai = maLoai;
    }
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }
    public Float getHeSo() {
        return this.heSo;
    }
    
    public void setHeSo(Float heSo) {
        this.heSo = heSo;
    }
    public Boolean getXoa() {
        return this.xoa;
    }
    
    public void setXoa(Boolean xoa) {
        this.xoa = xoa;
    }

@Override
    public String toString()
    {
        return this.tenLoai;
    }


}


