package quanlykhachsan.entity;
// Generated Jun 9, 2019 6:17:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieuthuephong generated by hbm2java
 */
public class Phieuthuephong  implements java.io.Serializable {


     private Integer maPhieuThue;
     private Integer maPhong;
     private Date ngayThue;
     private Float tongTien;
     private Boolean xoa;

    public Phieuthuephong() {
    }

    public Phieuthuephong(Integer maPhong, Date ngayThue, Float tongTien, Boolean xoa) {
       this.maPhong = maPhong;
       this.ngayThue = ngayThue;
       this.tongTien = tongTien;
       this.xoa = xoa;
    }
   
    public Integer getMaPhieuThue() {
        return this.maPhieuThue;
    }
    
    public void setMaPhieuThue(Integer maPhieuThue) {
        this.maPhieuThue = maPhieuThue;
    }
    public Integer getMaPhong() {
        return this.maPhong;
    }
    
    public void setMaPhong(Integer maPhong) {
        this.maPhong = maPhong;
    }
    public Date getNgayThue() {
        return this.ngayThue;
    }
    
    public void setNgayThue(Date ngayThue) {
        this.ngayThue = ngayThue;
    }
    public Float getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(Float tongTien) {
        this.tongTien = tongTien;
    }
    public Boolean getXoa() {
        return this.xoa;
    }
    
    public void setXoa(Boolean xoa) {
        this.xoa = xoa;
    }




}


