package quanlykhachsan.entity;
// Generated Jun 13, 2019 4:36:06 PM by Hibernate Tools 4.3.1



/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan implements java.io.Serializable {


     private Integer id;
     private String account;
     private String passwork;
     private Integer loaiTaiKhoan;
     private String tenNguoiDung;
     private Boolean xoa;

    public Taikhoan() {
    }

    public Taikhoan(String account, String passwork, Integer loaiTaiKhoan, String tenNguoiDung, Boolean xoa) {
       this.account = account;
       this.passwork = passwork;
       this.loaiTaiKhoan = loaiTaiKhoan;
       this.tenNguoiDung = tenNguoiDung;
       this.xoa = xoa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public String getPasswork() {
        return this.passwork;
    }
    
    public void setPasswork(String passwork) {
        this.passwork = passwork;
    }
    public Integer getLoaiTaiKhoan() {
        return this.loaiTaiKhoan;
    }
    
    public void setLoaiTaiKhoan(Integer loaiTaiKhoan) {
        this.loaiTaiKhoan = loaiTaiKhoan;
    }
    public String getTenNguoiDung() {
        return this.tenNguoiDung;
    }
    
    public void setTenNguoiDung(String tenNguoiDung) {
        this.tenNguoiDung = tenNguoiDung;
    }
    public Boolean getXoa() {
        return this.xoa;
    }
    
    public void setXoa(Boolean xoa) {
        this.xoa = xoa;
    }




}


